complete -c rv -f
complete -c rv -n "__fish_use_subcommand" -a "test" -d "Evaluate a command"
complete -c rv -n "__fish_use_subcommand" -a "explain" -d "Explain a decision"
complete -c rv -n "__fish_use_subcommand" -a "packs" -d "List and enable packs"
complete -c rv -n "__fish_use_subcommand" -a "policy" -d "Typed rules"
complete -c rv -n "__fish_use_subcommand" -a "scan" -d "Session forensics"
complete -c rv -n "__fish_use_subcommand" -a "allow-once" -d "Mint and redeem single-use unlock codes"
complete -c rv -n "__fish_use_subcommand" -a "allowlist" -d "Manage permanent user-layer exceptions"
complete -c rv -n "__fish_use_subcommand" -a "service" -d "Service status"
complete -c rv -n "__fish_use_subcommand" -a "hook" -d "Host hook child"
complete -c rv -n "__fish_use_subcommand" -a "setup" -d "Install hooks"
complete -c rv -n "__fish_use_subcommand" -a "uninstall" -d "Remove rv-owned files"
complete -c rv -n "__fish_use_subcommand" -a "doctor" -d "Read-only health"
complete -c rv -n "__fish_seen_subcommand_from allow-once" -a "mint" -d "Mint a code"
complete -c rv -n "__fish_seen_subcommand_from allow-once" -a "list" -d "List rows"
complete -c rv -n "__fish_seen_subcommand_from allow-once" -a "clear" -d "Clear rows"
complete -c rv -n "__fish_seen_subcommand_from allowlist" -a "add" -d "Add rule"
complete -c rv -n "__fish_seen_subcommand_from allowlist" -a "add-command" -d "Add exact command"
complete -c rv -n "__fish_seen_subcommand_from allowlist" -a "list" -d "List"
complete -c rv -n "__fish_seen_subcommand_from allowlist" -a "remove" -d "Remove"
complete -c rv -n "__fish_seen_subcommand_from allowlist" -a "validate" -d "Validate"
complete -c rv -n "__fish_seen_subcommand_from packs" -a "enable" -d "Enable a pack"
complete -c rv -n "__fish_seen_subcommand_from packs" -a "disable" -d "Disable a pack"
complete -c rv -n "__fish_seen_subcommand_from packs" -a "info" -d "Pack details"
complete -c rv -n "__fish_seen_subcommand_from policy" -a "show" -d "List rules"
complete -c rv -n "__fish_seen_subcommand_from policy" -a "draft" -d "Compile English"
complete -c rv -n "__fish_seen_subcommand_from policy" -a "validate" -d "Validate"
complete -c rv -n "__fish_seen_subcommand_from policy" -a "export" -d "Export"
complete -c rv -n "__fish_seen_subcommand_from policy" -a "apply" -d "Apply"
complete -c rv -n "__fish_seen_subcommand_from scan" -a "sessions" -d "Scan host session stores"
